/*
 * generated by Xtext
 */
package ufscar.compiladores2.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MusyGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MidiElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Midi");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMIDIKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBodyMidiBodyParserRuleCall_3_0 = (RuleCall)cBodyAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Midi:
		//	"MIDI" name=ID "{" body=MidiBody "}";
		@Override public ParserRule getRule() { return rule; }

		//"MIDI" name=ID "{" body=MidiBody "}"
		public Group getGroup() { return cGroup; }

		//"MIDI"
		public Keyword getMIDIKeyword_0() { return cMIDIKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//body=MidiBody
		public Assignment getBodyAssignment_3() { return cBodyAssignment_3; }

		//MidiBody
		public RuleCall getBodyMidiBodyParserRuleCall_3_0() { return cBodyMidiBodyParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class MidiBodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MidiBody");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMidiBodyAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cParamAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cParamParameterParserRuleCall_1_0 = (RuleCall)cParamAssignment_1.eContents().get(0);
		private final Assignment cChordsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cChordsDeclaredChordParserRuleCall_2_0 = (RuleCall)cChordsAssignment_2.eContents().get(0);
		private final Assignment cTracksAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTracksTrackParserRuleCall_3_0 = (RuleCall)cTracksAssignment_3.eContents().get(0);
		
		//MidiBody:
		//	{MidiBody} param+=Parameter* chords+=DeclaredChord* tracks+=Track*;
		@Override public ParserRule getRule() { return rule; }

		//{MidiBody} param+=Parameter* chords+=DeclaredChord* tracks+=Track*
		public Group getGroup() { return cGroup; }

		//{MidiBody}
		public Action getMidiBodyAction_0() { return cMidiBodyAction_0; }

		//param+=Parameter*
		public Assignment getParamAssignment_1() { return cParamAssignment_1; }

		//Parameter
		public RuleCall getParamParameterParserRuleCall_1_0() { return cParamParameterParserRuleCall_1_0; }

		//chords+=DeclaredChord*
		public Assignment getChordsAssignment_2() { return cChordsAssignment_2; }

		//DeclaredChord
		public RuleCall getChordsDeclaredChordParserRuleCall_2_0() { return cChordsDeclaredChordParserRuleCall_2_0; }

		//tracks+=Track*
		public Assignment getTracksAssignment_3() { return cTracksAssignment_3; }

		//Track
		public RuleCall getTracksTrackParserRuleCall_3_0() { return cTracksTrackParserRuleCall_3_0; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParameterBeatParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParameterTimeSignatureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cParameterTimeNoteParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cParameterTimePauseParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cParameterOctaveParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Parameter:
		//	ParameterBeat | ParameterTimeSignature | ParameterTimeNote | ParameterTimePause | ParameterOctave;
		@Override public ParserRule getRule() { return rule; }

		//ParameterBeat | ParameterTimeSignature | ParameterTimeNote | ParameterTimePause | ParameterOctave
		public Alternatives getAlternatives() { return cAlternatives; }

		//ParameterBeat
		public RuleCall getParameterBeatParserRuleCall_0() { return cParameterBeatParserRuleCall_0; }

		//ParameterTimeSignature
		public RuleCall getParameterTimeSignatureParserRuleCall_1() { return cParameterTimeSignatureParserRuleCall_1; }

		//ParameterTimeNote
		public RuleCall getParameterTimeNoteParserRuleCall_2() { return cParameterTimeNoteParserRuleCall_2; }

		//ParameterTimePause
		public RuleCall getParameterTimePauseParserRuleCall_3() { return cParameterTimePauseParserRuleCall_3; }

		//ParameterOctave
		public RuleCall getParameterOctaveParserRuleCall_4() { return cParameterOctaveParserRuleCall_4; }
	}

	public class ParameterBeatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterBeat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBPMKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBeatAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBeatINTTerminalRuleCall_2_0 = (RuleCall)cBeatAssignment_2.eContents().get(0);
		
		//ParameterBeat:
		//	"BPM" ":" beat=INT;
		@Override public ParserRule getRule() { return rule; }

		//"BPM" ":" beat=INT
		public Group getGroup() { return cGroup; }

		//"BPM"
		public Keyword getBPMKeyword_0() { return cBPMKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//beat=INT
		public Assignment getBeatAssignment_2() { return cBeatAssignment_2; }

		//INT
		public RuleCall getBeatINTTerminalRuleCall_2_0() { return cBeatINTTerminalRuleCall_2_0; }
	}

	public class ParameterTimeSignatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterTimeSignature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTIME_SIGNATUREKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTsigAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTsigTimeSignatureParserRuleCall_2_0 = (RuleCall)cTsigAssignment_2.eContents().get(0);
		
		//ParameterTimeSignature:
		//	"TIME_SIGNATURE" ":" tsig=TimeSignature;
		@Override public ParserRule getRule() { return rule; }

		//"TIME_SIGNATURE" ":" tsig=TimeSignature
		public Group getGroup() { return cGroup; }

		//"TIME_SIGNATURE"
		public Keyword getTIME_SIGNATUREKeyword_0() { return cTIME_SIGNATUREKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//tsig=TimeSignature
		public Assignment getTsigAssignment_2() { return cTsigAssignment_2; }

		//TimeSignature
		public RuleCall getTsigTimeSignatureParserRuleCall_2_0() { return cTsigTimeSignatureParserRuleCall_2_0; }
	}

	public class ParameterTimeNoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterTimeNote");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTIME_NOTEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTnTnParserRuleCall_2_0 = (RuleCall)cTnAssignment_2.eContents().get(0);
		
		//ParameterTimeNote:
		//	"TIME_NOTE" ":" tn=Tn;
		@Override public ParserRule getRule() { return rule; }

		//"TIME_NOTE" ":" tn=Tn
		public Group getGroup() { return cGroup; }

		//"TIME_NOTE"
		public Keyword getTIME_NOTEKeyword_0() { return cTIME_NOTEKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//tn=Tn
		public Assignment getTnAssignment_2() { return cTnAssignment_2; }

		//Tn
		public RuleCall getTnTnParserRuleCall_2_0() { return cTnTnParserRuleCall_2_0; }
	}

	public class ParameterTimePauseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterTimePause");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTIME_PAUSEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTpTpParserRuleCall_2_0 = (RuleCall)cTpAssignment_2.eContents().get(0);
		
		//ParameterTimePause:
		//	"TIME_PAUSE" ":" tp=Tp;
		@Override public ParserRule getRule() { return rule; }

		//"TIME_PAUSE" ":" tp=Tp
		public Group getGroup() { return cGroup; }

		//"TIME_PAUSE"
		public Keyword getTIME_PAUSEKeyword_0() { return cTIME_PAUSEKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//tp=Tp
		public Assignment getTpAssignment_2() { return cTpAssignment_2; }

		//Tp
		public RuleCall getTpTpParserRuleCall_2_0() { return cTpTpParserRuleCall_2_0; }
	}

	public class ParameterOctaveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterOctave");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOCTAVEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOctaveAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOctaveINTTerminalRuleCall_2_0 = (RuleCall)cOctaveAssignment_2.eContents().get(0);
		
		//ParameterOctave:
		//	"OCTAVE" ":" octave=INT;
		@Override public ParserRule getRule() { return rule; }

		//"OCTAVE" ":" octave=INT
		public Group getGroup() { return cGroup; }

		//"OCTAVE"
		public Keyword getOCTAVEKeyword_0() { return cOCTAVEKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//octave=INT
		public Assignment getOctaveAssignment_2() { return cOctaveAssignment_2; }

		//INT
		public RuleCall getOctaveINTTerminalRuleCall_2_0() { return cOctaveINTTerminalRuleCall_2_0; }
	}

	public class DeclaredChordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DeclaredChord");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChordKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCpChordParamsParserRuleCall_2_0 = (RuleCall)cCpAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//DeclaredChord:
		//	"chord" "(" cp=ChordParams ")" name=ID;
		@Override public ParserRule getRule() { return rule; }

		//"chord" "(" cp=ChordParams ")" name=ID
		public Group getGroup() { return cGroup; }

		//"chord"
		public Keyword getChordKeyword_0() { return cChordKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//cp=ChordParams
		public Assignment getCpAssignment_2() { return cCpAssignment_2; }

		//ChordParams
		public RuleCall getCpChordParamsParserRuleCall_2_0() { return cCpChordParamsParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
	}

	public class TrackElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Track");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTRACKKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIInstrumentParserRuleCall_3_0 = (RuleCall)cIAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTbodyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTbodyTrackBodyParserRuleCall_5_0 = (RuleCall)cTbodyAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Track:
		//	"TRACK" name=ID ":" i=Instrument "{" tbody=TrackBody "}";
		@Override public ParserRule getRule() { return rule; }

		//"TRACK" name=ID ":" i=Instrument "{" tbody=TrackBody "}"
		public Group getGroup() { return cGroup; }

		//"TRACK"
		public Keyword getTRACKKeyword_0() { return cTRACKKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//i=Instrument
		public Assignment getIAssignment_3() { return cIAssignment_3; }

		//Instrument
		public RuleCall getIInstrumentParserRuleCall_3_0() { return cIInstrumentParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//tbody=TrackBody
		public Assignment getTbodyAssignment_5() { return cTbodyAssignment_5; }

		//TrackBody
		public RuleCall getTbodyTrackBodyParserRuleCall_5_0() { return cTbodyTrackBodyParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class TrackBodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TrackBody");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBcAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBcBodyComponentParserRuleCall_0_0 = (RuleCall)cBcAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cBcAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cBcBodyComponentParserRuleCall_1_1_0 = (RuleCall)cBcAssignment_1_1.eContents().get(0);
		
		//TrackBody:
		//	bc+=BodyComponent ("," bc+=BodyComponent)*;
		@Override public ParserRule getRule() { return rule; }

		//bc+=BodyComponent ("," bc+=BodyComponent)*
		public Group getGroup() { return cGroup; }

		//bc+=BodyComponent
		public Assignment getBcAssignment_0() { return cBcAssignment_0; }

		//BodyComponent
		public RuleCall getBcBodyComponentParserRuleCall_0_0() { return cBcBodyComponentParserRuleCall_0_0; }

		//("," bc+=BodyComponent)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//bc+=BodyComponent
		public Assignment getBcAssignment_1_1() { return cBcAssignment_1_1; }

		//BodyComponent
		public RuleCall getBcBodyComponentParserRuleCall_1_1_0() { return cBcBodyComponentParserRuleCall_1_1_0; }
	}

	public class BodyComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BodyComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNoteAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNoteNoteParserRuleCall_0_0 = (RuleCall)cNoteAssignment_0.eContents().get(0);
		private final Assignment cBlockAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cBlockBlockParserRuleCall_1_0 = (RuleCall)cBlockAssignment_1.eContents().get(0);
		private final Assignment cChAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final CrossReference cChDeclaredChordCrossReference_2_0 = (CrossReference)cChAssignment_2.eContents().get(0);
		private final RuleCall cChDeclaredChordIDTerminalRuleCall_2_0_1 = (RuleCall)cChDeclaredChordCrossReference_2_0.eContents().get(1);
		
		////MoreTrackBody:
		////	{MoreTrackBody}
		////	(',' morebody += BodyComponent)+
		////;
		//BodyComponent: //cnote = CustomNote | 
		//	note=Note | block=Block | ch=[DeclaredChord];
		@Override public ParserRule getRule() { return rule; }

		////cnote = CustomNote | 
		//note=Note | block=Block | ch=[DeclaredChord]
		public Alternatives getAlternatives() { return cAlternatives; }

		////cnote = CustomNote | 
		//note=Note
		public Assignment getNoteAssignment_0() { return cNoteAssignment_0; }

		//Note
		public RuleCall getNoteNoteParserRuleCall_0_0() { return cNoteNoteParserRuleCall_0_0; }

		//block=Block
		public Assignment getBlockAssignment_1() { return cBlockAssignment_1; }

		//Block
		public RuleCall getBlockBlockParserRuleCall_1_0() { return cBlockBlockParserRuleCall_1_0; }

		//ch=[DeclaredChord]
		public Assignment getChAssignment_2() { return cChAssignment_2; }

		//[DeclaredChord]
		public CrossReference getChDeclaredChordCrossReference_2_0() { return cChDeclaredChordCrossReference_2_0; }

		//ID
		public RuleCall getChDeclaredChordIDTerminalRuleCall_2_0_1() { return cChDeclaredChordIDTerminalRuleCall_2_0_1; }
	}

	public class BlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Block");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBLOCKKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBlockbodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBlockbodyTrackBodyParserRuleCall_3_0 = (RuleCall)cBlockbodyAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Block:
		//	"BLOCK" name=ID "{" blockbody+=TrackBody* "}";
		@Override public ParserRule getRule() { return rule; }

		//"BLOCK" name=ID "{" blockbody+=TrackBody* "}"
		public Group getGroup() { return cGroup; }

		//"BLOCK"
		public Keyword getBLOCKKeyword_0() { return cBLOCKKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//blockbody+=TrackBody*
		public Assignment getBlockbodyAssignment_3() { return cBlockbodyAssignment_3; }

		//TrackBody
		public RuleCall getBlockbodyTrackBodyParserRuleCall_3_0() { return cBlockbodyTrackBodyParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TimeSignatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TimeSignature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cQuantityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cQuantityINTTerminalRuleCall_0_0 = (RuleCall)cQuantityAssignment_0.eContents().get(0);
		private final Keyword cSolidusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNoteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNoteINTTerminalRuleCall_2_0 = (RuleCall)cNoteAssignment_2.eContents().get(0);
		
		//TimeSignature:
		//	quantity=INT "/" note=INT;
		@Override public ParserRule getRule() { return rule; }

		//quantity=INT "/" note=INT
		public Group getGroup() { return cGroup; }

		//quantity=INT
		public Assignment getQuantityAssignment_0() { return cQuantityAssignment_0; }

		//INT
		public RuleCall getQuantityINTTerminalRuleCall_0_0() { return cQuantityINTTerminalRuleCall_0_0; }

		//"/"
		public Keyword getSolidusKeyword_1() { return cSolidusKeyword_1; }

		//note=INT
		public Assignment getNoteAssignment_2() { return cNoteAssignment_2; }

		//INT
		public RuleCall getNoteINTTerminalRuleCall_2_0() { return cNoteINTTerminalRuleCall_2_0; }
	}

	public class TpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Tp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cSbKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cMKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cSmKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cClKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cScKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cFKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cSfKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		
		//Tp:
		//	"sb" | "m" | "sm" | "cl" | "sc" | "f" | "sf";
		@Override public ParserRule getRule() { return rule; }

		//"sb" | "m" | "sm" | "cl" | "sc" | "f" | "sf"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"sb"
		public Keyword getSbKeyword_0() { return cSbKeyword_0; }

		//"m"
		public Keyword getMKeyword_1() { return cMKeyword_1; }

		//"sm"
		public Keyword getSmKeyword_2() { return cSmKeyword_2; }

		//"cl"
		public Keyword getClKeyword_3() { return cClKeyword_3; }

		//"sc"
		public Keyword getScKeyword_4() { return cScKeyword_4; }

		//"f"
		public Keyword getFKeyword_5() { return cFKeyword_5; }

		//"sf"
		public Keyword getSfKeyword_6() { return cSfKeyword_6; }
	}

	public class TnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Tn");
		private final RuleCall cTpParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Tn:
		//	Tp;
		@Override public ParserRule getRule() { return rule; }

		//Tp
		public RuleCall getTpParserRuleCall() { return cTpParserRuleCall; }
	}

	public class ChordParamsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ChordParams");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCnoteAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCnoteNoteParserRuleCall_0_0 = (RuleCall)cCnoteAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cCnoteAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cCnoteNoteParserRuleCall_1_1_0 = (RuleCall)cCnoteAssignment_1_1.eContents().get(0);
		
		////CustomNote:
		////	Note '(' CustomNoteParam ')'
		////;
		//ChordParams:
		//	cnote+=Note ("," cnote+=Note)*;
		@Override public ParserRule getRule() { return rule; }

		//cnote+=Note ("," cnote+=Note)*
		public Group getGroup() { return cGroup; }

		//cnote+=Note
		public Assignment getCnoteAssignment_0() { return cCnoteAssignment_0; }

		//Note
		public RuleCall getCnoteNoteParserRuleCall_0_0() { return cCnoteNoteParserRuleCall_0_0; }

		//("," cnote+=Note)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//cnote+=Note
		public Assignment getCnoteAssignment_1_1() { return cCnoteAssignment_1_1; }

		//Note
		public RuleCall getCnoteNoteParserRuleCall_1_1_0() { return cCnoteNoteParserRuleCall_1_1_0; }
	}

	public class NoteLetterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NoteLetter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cCKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cDKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cFKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cGKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cAKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cBKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		
		//NoteLetter:
		//	"C" | "D" | "E" | "F" | "G" | "A" | "B";
		@Override public ParserRule getRule() { return rule; }

		//"C" | "D" | "E" | "F" | "G" | "A" | "B"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"C"
		public Keyword getCKeyword_0() { return cCKeyword_0; }

		//"D"
		public Keyword getDKeyword_1() { return cDKeyword_1; }

		//"E"
		public Keyword getEKeyword_2() { return cEKeyword_2; }

		//"F"
		public Keyword getFKeyword_3() { return cFKeyword_3; }

		//"G"
		public Keyword getGKeyword_4() { return cGKeyword_4; }

		//"A"
		public Keyword getAKeyword_5() { return cAKeyword_5; }

		//"B"
		public Keyword getBKeyword_6() { return cBKeyword_6; }
	}

	public class AccidentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Accident");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cBKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Accident:
		//	"#" | "b";
		@Override public ParserRule getRule() { return rule; }

		//"#" | "b"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"#"
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }

		//"b"
		public Keyword getBKeyword_1() { return cBKeyword_1; }
	}

	public class NoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Note");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNlAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNlNoteLetterParserRuleCall_0_0 = (RuleCall)cNlAssignment_0.eContents().get(0);
		private final Assignment cAccAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAccAccidentParserRuleCall_1_0 = (RuleCall)cAccAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCnpAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCnpCustomNoteParamParserRuleCall_2_1_0 = (RuleCall)cCnpAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Note:
		//	nl=NoteLetter acc=Accident? ("(" cnp=CustomNoteParam ")")?;
		@Override public ParserRule getRule() { return rule; }

		//nl=NoteLetter acc=Accident? ("(" cnp=CustomNoteParam ")")?
		public Group getGroup() { return cGroup; }

		//nl=NoteLetter
		public Assignment getNlAssignment_0() { return cNlAssignment_0; }

		//NoteLetter
		public RuleCall getNlNoteLetterParserRuleCall_0_0() { return cNlNoteLetterParserRuleCall_0_0; }

		//acc=Accident?
		public Assignment getAccAssignment_1() { return cAccAssignment_1; }

		//Accident
		public RuleCall getAccAccidentParserRuleCall_1_0() { return cAccAccidentParserRuleCall_1_0; }

		//("(" cnp=CustomNoteParam ")")?
		public Group getGroup_2() { return cGroup_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }

		//cnp=CustomNoteParam
		public Assignment getCnpAssignment_2_1() { return cCnpAssignment_2_1; }

		//CustomNoteParam
		public RuleCall getCnpCustomNoteParamParserRuleCall_2_1_0() { return cCnpCustomNoteParamParserRuleCall_2_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
	}

	public class InstrumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instrument");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPIANOKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cGUITARKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cELETRICGUITARKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cBASSKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cSAXKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cVIOLINKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cDRUMSKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		
		//Instrument:
		//	"PIANO" | "GUITAR" | "ELETRIC GUITAR" | "BASS" | "SAX" | "VIOLIN" | "DRUMS";
		@Override public ParserRule getRule() { return rule; }

		//"PIANO" | "GUITAR" | "ELETRIC GUITAR" | "BASS" | "SAX" | "VIOLIN" | "DRUMS"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"PIANO"
		public Keyword getPIANOKeyword_0() { return cPIANOKeyword_0; }

		//"GUITAR"
		public Keyword getGUITARKeyword_1() { return cGUITARKeyword_1; }

		//"ELETRIC GUITAR"
		public Keyword getELETRICGUITARKeyword_2() { return cELETRICGUITARKeyword_2; }

		//"BASS"
		public Keyword getBASSKeyword_3() { return cBASSKeyword_3; }

		//"SAX"
		public Keyword getSAXKeyword_4() { return cSAXKeyword_4; }

		//"VIOLIN"
		public Keyword getVIOLINKeyword_5() { return cVIOLINKeyword_5; }

		//"DRUMS"
		public Keyword getDRUMSKeyword_6() { return cDRUMSKeyword_6; }
	}

	public class CustomNoteParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CustomNoteParam");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cOctaveAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cOctaveINTTerminalRuleCall_0_0_0 = (RuleCall)cOctaveAssignment_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDurationAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDurationTnParserRuleCall_0_2_0 = (RuleCall)cDurationAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cDurationAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cDurationTnParserRuleCall_1_0_0 = (RuleCall)cDurationAssignment_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cOctaveAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cOctaveINTTerminalRuleCall_1_2_0 = (RuleCall)cOctaveAssignment_1_2.eContents().get(0);
		private final Assignment cOctaveAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cOctaveINTTerminalRuleCall_2_0 = (RuleCall)cOctaveAssignment_2.eContents().get(0);
		private final Assignment cDurationAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cDurationTnParserRuleCall_3_0 = (RuleCall)cDurationAssignment_3.eContents().get(0);
		
		//CustomNoteParam:
		//	octave=INT "," duration=Tn | duration=Tn "," octave=INT | octave=INT | duration=Tn;
		@Override public ParserRule getRule() { return rule; }

		//octave=INT "," duration=Tn | duration=Tn "," octave=INT | octave=INT | duration=Tn
		public Alternatives getAlternatives() { return cAlternatives; }

		//octave=INT "," duration=Tn
		public Group getGroup_0() { return cGroup_0; }

		//octave=INT
		public Assignment getOctaveAssignment_0_0() { return cOctaveAssignment_0_0; }

		//INT
		public RuleCall getOctaveINTTerminalRuleCall_0_0_0() { return cOctaveINTTerminalRuleCall_0_0_0; }

		//","
		public Keyword getCommaKeyword_0_1() { return cCommaKeyword_0_1; }

		//duration=Tn
		public Assignment getDurationAssignment_0_2() { return cDurationAssignment_0_2; }

		//Tn
		public RuleCall getDurationTnParserRuleCall_0_2_0() { return cDurationTnParserRuleCall_0_2_0; }

		//duration=Tn "," octave=INT
		public Group getGroup_1() { return cGroup_1; }

		//duration=Tn
		public Assignment getDurationAssignment_1_0() { return cDurationAssignment_1_0; }

		//Tn
		public RuleCall getDurationTnParserRuleCall_1_0_0() { return cDurationTnParserRuleCall_1_0_0; }

		//","
		public Keyword getCommaKeyword_1_1() { return cCommaKeyword_1_1; }

		//octave=INT
		public Assignment getOctaveAssignment_1_2() { return cOctaveAssignment_1_2; }

		//INT
		public RuleCall getOctaveINTTerminalRuleCall_1_2_0() { return cOctaveINTTerminalRuleCall_1_2_0; }

		//octave=INT
		public Assignment getOctaveAssignment_2() { return cOctaveAssignment_2; }

		//INT
		public RuleCall getOctaveINTTerminalRuleCall_2_0() { return cOctaveINTTerminalRuleCall_2_0; }

		//duration=Tn
		public Assignment getDurationAssignment_3() { return cDurationAssignment_3; }

		//Tn
		public RuleCall getDurationTnParserRuleCall_3_0() { return cDurationTnParserRuleCall_3_0; }
	}
	
	
	private final MidiElements pMidi;
	private final MidiBodyElements pMidiBody;
	private final ParameterElements pParameter;
	private final ParameterBeatElements pParameterBeat;
	private final ParameterTimeSignatureElements pParameterTimeSignature;
	private final ParameterTimeNoteElements pParameterTimeNote;
	private final ParameterTimePauseElements pParameterTimePause;
	private final ParameterOctaveElements pParameterOctave;
	private final DeclaredChordElements pDeclaredChord;
	private final TrackElements pTrack;
	private final TrackBodyElements pTrackBody;
	private final BodyComponentElements pBodyComponent;
	private final BlockElements pBlock;
	private final TimeSignatureElements pTimeSignature;
	private final TpElements pTp;
	private final TnElements pTn;
	private final ChordParamsElements pChordParams;
	private final NoteLetterElements pNoteLetter;
	private final AccidentElements pAccident;
	private final NoteElements pNote;
	private final InstrumentElements pInstrument;
	private final CustomNoteParamElements pCustomNoteParam;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MusyGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMidi = new MidiElements();
		this.pMidiBody = new MidiBodyElements();
		this.pParameter = new ParameterElements();
		this.pParameterBeat = new ParameterBeatElements();
		this.pParameterTimeSignature = new ParameterTimeSignatureElements();
		this.pParameterTimeNote = new ParameterTimeNoteElements();
		this.pParameterTimePause = new ParameterTimePauseElements();
		this.pParameterOctave = new ParameterOctaveElements();
		this.pDeclaredChord = new DeclaredChordElements();
		this.pTrack = new TrackElements();
		this.pTrackBody = new TrackBodyElements();
		this.pBodyComponent = new BodyComponentElements();
		this.pBlock = new BlockElements();
		this.pTimeSignature = new TimeSignatureElements();
		this.pTp = new TpElements();
		this.pTn = new TnElements();
		this.pChordParams = new ChordParamsElements();
		this.pNoteLetter = new NoteLetterElements();
		this.pAccident = new AccidentElements();
		this.pNote = new NoteElements();
		this.pInstrument = new InstrumentElements();
		this.pCustomNoteParam = new CustomNoteParamElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ufscar.compiladores2.Musy".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Midi:
	//	"MIDI" name=ID "{" body=MidiBody "}";
	public MidiElements getMidiAccess() {
		return pMidi;
	}
	
	public ParserRule getMidiRule() {
		return getMidiAccess().getRule();
	}

	//MidiBody:
	//	{MidiBody} param+=Parameter* chords+=DeclaredChord* tracks+=Track*;
	public MidiBodyElements getMidiBodyAccess() {
		return pMidiBody;
	}
	
	public ParserRule getMidiBodyRule() {
		return getMidiBodyAccess().getRule();
	}

	//Parameter:
	//	ParameterBeat | ParameterTimeSignature | ParameterTimeNote | ParameterTimePause | ParameterOctave;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//ParameterBeat:
	//	"BPM" ":" beat=INT;
	public ParameterBeatElements getParameterBeatAccess() {
		return pParameterBeat;
	}
	
	public ParserRule getParameterBeatRule() {
		return getParameterBeatAccess().getRule();
	}

	//ParameterTimeSignature:
	//	"TIME_SIGNATURE" ":" tsig=TimeSignature;
	public ParameterTimeSignatureElements getParameterTimeSignatureAccess() {
		return pParameterTimeSignature;
	}
	
	public ParserRule getParameterTimeSignatureRule() {
		return getParameterTimeSignatureAccess().getRule();
	}

	//ParameterTimeNote:
	//	"TIME_NOTE" ":" tn=Tn;
	public ParameterTimeNoteElements getParameterTimeNoteAccess() {
		return pParameterTimeNote;
	}
	
	public ParserRule getParameterTimeNoteRule() {
		return getParameterTimeNoteAccess().getRule();
	}

	//ParameterTimePause:
	//	"TIME_PAUSE" ":" tp=Tp;
	public ParameterTimePauseElements getParameterTimePauseAccess() {
		return pParameterTimePause;
	}
	
	public ParserRule getParameterTimePauseRule() {
		return getParameterTimePauseAccess().getRule();
	}

	//ParameterOctave:
	//	"OCTAVE" ":" octave=INT;
	public ParameterOctaveElements getParameterOctaveAccess() {
		return pParameterOctave;
	}
	
	public ParserRule getParameterOctaveRule() {
		return getParameterOctaveAccess().getRule();
	}

	//DeclaredChord:
	//	"chord" "(" cp=ChordParams ")" name=ID;
	public DeclaredChordElements getDeclaredChordAccess() {
		return pDeclaredChord;
	}
	
	public ParserRule getDeclaredChordRule() {
		return getDeclaredChordAccess().getRule();
	}

	//Track:
	//	"TRACK" name=ID ":" i=Instrument "{" tbody=TrackBody "}";
	public TrackElements getTrackAccess() {
		return pTrack;
	}
	
	public ParserRule getTrackRule() {
		return getTrackAccess().getRule();
	}

	//TrackBody:
	//	bc+=BodyComponent ("," bc+=BodyComponent)*;
	public TrackBodyElements getTrackBodyAccess() {
		return pTrackBody;
	}
	
	public ParserRule getTrackBodyRule() {
		return getTrackBodyAccess().getRule();
	}

	////MoreTrackBody:
	////	{MoreTrackBody}
	////	(',' morebody += BodyComponent)+
	////;
	//BodyComponent: //cnote = CustomNote | 
	//	note=Note | block=Block | ch=[DeclaredChord];
	public BodyComponentElements getBodyComponentAccess() {
		return pBodyComponent;
	}
	
	public ParserRule getBodyComponentRule() {
		return getBodyComponentAccess().getRule();
	}

	//Block:
	//	"BLOCK" name=ID "{" blockbody+=TrackBody* "}";
	public BlockElements getBlockAccess() {
		return pBlock;
	}
	
	public ParserRule getBlockRule() {
		return getBlockAccess().getRule();
	}

	//TimeSignature:
	//	quantity=INT "/" note=INT;
	public TimeSignatureElements getTimeSignatureAccess() {
		return pTimeSignature;
	}
	
	public ParserRule getTimeSignatureRule() {
		return getTimeSignatureAccess().getRule();
	}

	//Tp:
	//	"sb" | "m" | "sm" | "cl" | "sc" | "f" | "sf";
	public TpElements getTpAccess() {
		return pTp;
	}
	
	public ParserRule getTpRule() {
		return getTpAccess().getRule();
	}

	//Tn:
	//	Tp;
	public TnElements getTnAccess() {
		return pTn;
	}
	
	public ParserRule getTnRule() {
		return getTnAccess().getRule();
	}

	////CustomNote:
	////	Note '(' CustomNoteParam ')'
	////;
	//ChordParams:
	//	cnote+=Note ("," cnote+=Note)*;
	public ChordParamsElements getChordParamsAccess() {
		return pChordParams;
	}
	
	public ParserRule getChordParamsRule() {
		return getChordParamsAccess().getRule();
	}

	//NoteLetter:
	//	"C" | "D" | "E" | "F" | "G" | "A" | "B";
	public NoteLetterElements getNoteLetterAccess() {
		return pNoteLetter;
	}
	
	public ParserRule getNoteLetterRule() {
		return getNoteLetterAccess().getRule();
	}

	//Accident:
	//	"#" | "b";
	public AccidentElements getAccidentAccess() {
		return pAccident;
	}
	
	public ParserRule getAccidentRule() {
		return getAccidentAccess().getRule();
	}

	//Note:
	//	nl=NoteLetter acc=Accident? ("(" cnp=CustomNoteParam ")")?;
	public NoteElements getNoteAccess() {
		return pNote;
	}
	
	public ParserRule getNoteRule() {
		return getNoteAccess().getRule();
	}

	//Instrument:
	//	"PIANO" | "GUITAR" | "ELETRIC GUITAR" | "BASS" | "SAX" | "VIOLIN" | "DRUMS";
	public InstrumentElements getInstrumentAccess() {
		return pInstrument;
	}
	
	public ParserRule getInstrumentRule() {
		return getInstrumentAccess().getRule();
	}

	//CustomNoteParam:
	//	octave=INT "," duration=Tn | duration=Tn "," octave=INT | octave=INT | duration=Tn;
	public CustomNoteParamElements getCustomNoteParamAccess() {
		return pCustomNoteParam;
	}
	
	public ParserRule getCustomNoteParamRule() {
		return getCustomNoteParamAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
