/*
 * generated by Xtext
 */
package ufscar.compiladores2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MusyUiModule extends ufscar.compiladores2.ui.AbstractMusyUiModule {
	public MusyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
