/**
 * generated by Xtext
 */
package ufscar.compiladores2.validation;

import org.eclipse.xtext.validation.Check;
import ufscar.compiladores2.musy.ParameterBeat;
import ufscar.compiladores2.validation.AbstractMusyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MusyValidator extends AbstractMusyValidator {
  @Check
  public void checkBPM(final ParameterBeat p) {
    boolean _or = false;
    int _beat = p.getBeat();
    boolean _lessThan = (_beat < 1);
    if (_lessThan) {
      _or = true;
    } else {
      int _beat_1 = p.getBeat();
      boolean _greaterThan = (_beat_1 > 500);
      _or = _greaterThan;
    }
    if (_or) {
      this.error("Beat must be between 1 and 500", null);
    }
  }
}
