/*
 * generated by Xtext
 */
package ufscar.compiladores2;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MusyStandaloneSetup extends MusyStandaloneSetupGenerated{

	public static void doSetup() {
		new MusyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

