/*
 * generated by Xtext
 */
package ufscar.compiladores2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MusyRuntimeModule extends ufscar.compiladores2.AbstractMusyRuntimeModule {

}
