/*
 * generated by Xtext
 */
package ufscar.compiladores2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ufscar.compiladores2.services.MusyGrammarAccess;

public class MusyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MusyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ufscar.compiladores2.parser.antlr.internal.InternalMusyParser createParser(XtextTokenStream stream) {
		return new ufscar.compiladores2.parser.antlr.internal.InternalMusyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Midi";
	}
	
	public MusyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MusyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
