/*
 * generated by Xtext
 */
package ufscar.compiladores2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMusyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ufscar.compiladores2.musy.MusyPackage.eINSTANCE);
		return result;
	}
}
