/**
 * generated by Xtext
 */
package ufscar.compiladores2.ui.contentassist;

import ufscar.compiladores2.ui.contentassist.AbstractMusyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MusyProposalProvider extends AbstractMusyProposalProvider {
}
