/*
 * generated by Xtext
 */
package ufscar.compiladores2.validation

import org.eclipse.xtext.validation.Check
import ufscar.compiladores2.musy.ParameterBeat

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MusyValidator extends AbstractMusyValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def void checkBPM(ParameterBeat p) {
		if(p.beat < 1 || p.beat > 500)
			error("Beat must be between 1 and 500", null);
	}
}
